// <auto-generated />
using System;
using BeltmanSoftwareDesign.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeltmanSoftwareDesign.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240221071455_voor de zekerheid")]
    partial class voordezekerheid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.BankStatement", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int?>("Bank")
                        .HasColumnType("int");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("CreditType")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EigenRekeningNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBelasting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBelastingBTW")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHuur")
                        .HasColumnType("bit");

                    b.Property<double>("KleineOndernemersRegeling")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<string>("TegenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TegenRekeningNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolgNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("BankStatements");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.BankStatementExpense", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("BankStatementId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExpenseId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("BankStatementId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("BankStatementExpenses");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.BankStatementInvoice", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("BankStatementId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("BankStatementId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("BankStatementInvoices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ClientBearer", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("ClientDeviceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientIpAddressId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("id");

                    b.HasIndex("ClientDeviceId");

                    b.HasIndex("ClientIpAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("ClientBearers");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ClientDevice", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("id");

                    b.ToTable("ClientDevices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ClientDeviceProperty", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("ClientDeviceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("id");

                    b.HasIndex("ClientDeviceId");

                    b.ToTable("ClientDeviceProperties");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ClientIpAddress", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("id");

                    b.ToTable("ClientLocations");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Company", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BtwNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Iban")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("KvkNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayNL_ApiToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayNL_ServiceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Place")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Postalcode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("id");

                    b.HasIndex("CountryId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.CompanyUser", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Eigenaar")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Country", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Customer", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postalcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Publiekelijk")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Document", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DocumentTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.DocumentAttachment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileMD5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentAttachments");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.DocumentType", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Email", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EmailDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailHtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailIndex")
                        .HasColumnType("int");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTextBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Expense", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateKapot")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ExpenseTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPayedInCash")
                        .HasColumnType("bit");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<double>("Restwaarde")
                        .HasColumnType("float");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpenseAttachment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailUniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ExpenseId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileMD5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseAttachments");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpensePrice", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("ExpenseId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long?>("TaxRateId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("TaxRateId");

                    b.ToTable("ExpensePrices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpenseProduct", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long?>("ExpenseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExpenseProducts");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpenseType", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("AfschrijfKostenType")
                        .HasColumnType("int");

                    b.Property<int>("BedrijfsKostenType")
                        .HasColumnType("int");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHalfTellen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRepresentatieKosten")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVolledigeKosten")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Experience", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int?>("AmountUur")
                        .HasColumnType("int");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Stop")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExperienceAttachment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("ExperienceId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileMD5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("Spotlight")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("ExperienceAttachments");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExperienceTechnology", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("ExperienceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TechnologyId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ExperienceTechnologies");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Invoice", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("InvoiceTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPayedInCash")
                        .HasColumnType("bit");

                    b.Property<long?>("IsPayedInCash_By_CompanyUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceTypeId");

                    b.HasIndex("IsPayedInCash_By_CompanyUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceAttachment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileMD5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInvoicePDF")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkorderPDF")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceAttachments");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceEmail", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateEmailGezien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInvoiceGezien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateVerzonden")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailGezien")
                        .HasColumnType("bit");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InvoiceGezien")
                        .HasColumnType("bit");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceEmails");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoicePrice", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long?>("TaxRateId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TaxRateId");

                    b.ToTable("InvoicePrices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceProduct", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceProducts");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceRow", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDiscountRow")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("PricePerPiece")
                        .HasColumnType("float");

                    b.Property<long>("TaxRateId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TaxRateId");

                    b.ToTable("InvoiceRows");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceTransaction", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TransactionId");

                    b.ToTable("InvoiceTransactions");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceType", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("InvoiceTypes");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceWorkorder", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkorderId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("WorkorderId");

                    b.ToTable("InvoiceWorkorders");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ProductPrice", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TaxRateId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TaxRateId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Project", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Publiekelijk")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Rate", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("Tax")
                        .HasColumnType("float");

                    b.Property<long>("TaxRateId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TaxRateId");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Residence", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("WOZWaarde")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Setting", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValueDouble")
                        .HasColumnType("float");

                    b.Property<string>("ValueString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Supplier", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postalcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Publiekelijk")
                        .HasColumnType("bit");

                    b.Property<string>("RekeningNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TaxRate", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Technology", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsProgrammeerTaal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("id");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TechnologyAttachment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("FileMD5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<long>("TechnologyId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("TechnologyAttachments");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TrafficRegistration", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KilometerStart")
                        .HasColumnType("float");

                    b.Property<double>("KilometerStop")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("TrafficRegistrations");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Transaction", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCancelled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePayed")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPayed")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TransactionLog", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TransactionLogParameter", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TransactionLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("TransactionLogId");

                    b.ToTable("TransactionLogParameters");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TransactionParameter", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionParameters");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("CurrentCompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Workorder", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Stop")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RateId");

                    b.ToTable("Workorders");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.WorkorderAttachment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("FileMD5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkorderId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("WorkorderId");

                    b.ToTable("WorkorderAttachments");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.BankStatement", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("BankStatements")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.BankStatementExpense", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.BankStatement", "BankStatement")
                        .WithMany("BankStatementExpenses")
                        .HasForeignKey("BankStatementId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Expense", "Expense")
                        .WithMany("BankStatementExpenses")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BankStatement");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.BankStatementInvoice", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.BankStatement", "BankStatement")
                        .WithMany("BankStatementInvoices")
                        .HasForeignKey("BankStatementId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Invoice", "Invoice")
                        .WithMany("BankStatementInvoices")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BankStatement");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ClientBearer", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.ClientDevice", "ClientDevice")
                        .WithMany("ClientBearers")
                        .HasForeignKey("ClientDeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.ClientIpAddress", "ClientIpAddress")
                        .WithMany("ClientBearers")
                        .HasForeignKey("ClientIpAddressId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.User", "User")
                        .WithMany("ClientBearers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClientDevice");

                    b.Navigation("ClientIpAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ClientDeviceProperty", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.ClientDevice", "ClientDevice")
                        .WithMany("ClientDeviceProperties")
                        .HasForeignKey("ClientDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientDevice");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Company", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Country", "Country")
                        .WithMany("Companies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.CompanyUser", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.User", "User")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Customer", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Country", "Country")
                        .WithMany("Customers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Document", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Documents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Supplier", "Supplier")
                        .WithMany("Documents")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("DocumentType");

                    b.Navigation("Project");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.DocumentAttachment", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Document", "Document")
                        .WithMany("DocumentAttachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.DocumentType", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Email", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Expense", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Expenses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Customer", "Customer")
                        .WithMany("Expenses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.ExpenseType", "ExpenseType")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Project", "Project")
                        .WithMany("Expenses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Supplier", "Supplier")
                        .WithMany("Expenses")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("ExpenseType");

                    b.Navigation("Project");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpenseAttachment", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Expense", "Expense")
                        .WithMany("ExpenseAttachments")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpensePrice", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Expense", "Expense")
                        .WithMany("ExpensePrices")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.TaxRate", "TaxRate")
                        .WithMany("ExpensePrices")
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Expense");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpenseProduct", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Expense", "Expense")
                        .WithMany("ExpenseProducts")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Product", "Product")
                        .WithMany("ExpenseProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Expense");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpenseType", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("ExpenseTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Invoice", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Invoices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.InvoiceType", "InvoiceType")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.CompanyUser", "IsPayedInCash_By_CompanyUser")
                        .WithMany("Invoices_SetToPayed")
                        .HasForeignKey("IsPayedInCash_By_CompanyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Project", "Project")
                        .WithMany("Invoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("InvoiceType");

                    b.Navigation("IsPayedInCash_By_CompanyUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceAttachment", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceAttachments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceEmail", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceEmails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoicePrice", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoicePrices")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.TaxRate", "TaxRate")
                        .WithMany("InvoicePrices")
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Invoice");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceProduct", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Product", "Product")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceRow", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceRows")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.TaxRate", "TaxRate")
                        .WithMany("InvoiceRows")
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceTransaction", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceTransactions")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Transaction", "Transaction")
                        .WithMany("InvoiceTransactions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceType", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("InvoiceTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceWorkorder", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceWorkorders")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Workorder", "Workorder")
                        .WithMany("InvoiceWorkorders")
                        .HasForeignKey("WorkorderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Invoice");

                    b.Navigation("Workorder");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Product", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ProductPrice", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.TaxRate", "TaxRate")
                        .WithMany("ProductPrices")
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Product");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Project", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Rate", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Rates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.TaxRate", "TaxRate")
                        .WithMany("Rates")
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Residence", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Residences")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Setting", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Settings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Supplier", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Suppliers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Country", "Country")
                        .WithMany("Suppliers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TaxRate", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("TaxRates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Country", "Country")
                        .WithMany("TaxRates")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TrafficRegistration", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("TrafficRegistrations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Transaction", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Transactions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TransactionLog", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Transaction", "Transaction")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TransactionLogParameter", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.TransactionLog", "TransactionLog")
                        .WithMany("TransactionLogParameters")
                        .HasForeignKey("TransactionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionLog");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TransactionParameter", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Transaction", "Transaction")
                        .WithMany("TransactionParameters")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.User", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "CurrentCompany")
                        .WithMany("CurrentUsers")
                        .HasForeignKey("CurrentCompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentCompany");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Workorder", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Company", "Company")
                        .WithMany("Workorders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Customer", "Customer")
                        .WithMany("Workorders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Project", "Project")
                        .WithMany("Workorders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Rate", "Rate")
                        .WithMany("Workorders")
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("Project");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.WorkorderAttachment", b =>
                {
                    b.HasOne("BeltmanSoftwareDesign.Data.Entities.Workorder", "Workorder")
                        .WithMany("WorkorderAttachments")
                        .HasForeignKey("WorkorderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workorder");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.BankStatement", b =>
                {
                    b.Navigation("BankStatementExpenses");

                    b.Navigation("BankStatementInvoices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ClientDevice", b =>
                {
                    b.Navigation("ClientBearers");

                    b.Navigation("ClientDeviceProperties");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ClientIpAddress", b =>
                {
                    b.Navigation("ClientBearers");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Company", b =>
                {
                    b.Navigation("BankStatements");

                    b.Navigation("CompanyUsers");

                    b.Navigation("CurrentUsers");

                    b.Navigation("Customers");

                    b.Navigation("DocumentTypes");

                    b.Navigation("Documents");

                    b.Navigation("ExpenseTypes");

                    b.Navigation("Expenses");

                    b.Navigation("InvoiceTypes");

                    b.Navigation("Invoices");

                    b.Navigation("Products");

                    b.Navigation("Projects");

                    b.Navigation("Rates");

                    b.Navigation("Residences");

                    b.Navigation("Settings");

                    b.Navigation("Suppliers");

                    b.Navigation("TaxRates");

                    b.Navigation("TrafficRegistrations");

                    b.Navigation("Transactions");

                    b.Navigation("Workorders");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.CompanyUser", b =>
                {
                    b.Navigation("Invoices_SetToPayed");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Country", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Customers");

                    b.Navigation("Suppliers");

                    b.Navigation("TaxRates");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Customer", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Expenses");

                    b.Navigation("Invoices");

                    b.Navigation("Projects");

                    b.Navigation("Workorders");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Document", b =>
                {
                    b.Navigation("DocumentAttachments");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Expense", b =>
                {
                    b.Navigation("BankStatementExpenses");

                    b.Navigation("ExpenseAttachments");

                    b.Navigation("ExpensePrices");

                    b.Navigation("ExpenseProducts");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.ExpenseType", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Invoice", b =>
                {
                    b.Navigation("BankStatementInvoices");

                    b.Navigation("InvoiceAttachments");

                    b.Navigation("InvoiceEmails");

                    b.Navigation("InvoicePrices");

                    b.Navigation("InvoiceProducts");

                    b.Navigation("InvoiceRows");

                    b.Navigation("InvoiceTransactions");

                    b.Navigation("InvoiceWorkorders");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.InvoiceType", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Product", b =>
                {
                    b.Navigation("ExpenseProducts");

                    b.Navigation("InvoiceProducts");

                    b.Navigation("ProductPrices");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Project", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Expenses");

                    b.Navigation("Invoices");

                    b.Navigation("Workorders");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Rate", b =>
                {
                    b.Navigation("Workorders");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Supplier", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Expenses");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TaxRate", b =>
                {
                    b.Navigation("ExpensePrices");

                    b.Navigation("InvoicePrices");

                    b.Navigation("InvoiceRows");

                    b.Navigation("ProductPrices");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Transaction", b =>
                {
                    b.Navigation("InvoiceTransactions");

                    b.Navigation("TransactionLogs");

                    b.Navigation("TransactionParameters");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.TransactionLog", b =>
                {
                    b.Navigation("TransactionLogParameters");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.User", b =>
                {
                    b.Navigation("ClientBearers");

                    b.Navigation("CompanyUsers");
                });

            modelBuilder.Entity("BeltmanSoftwareDesign.Data.Entities.Workorder", b =>
                {
                    b.Navigation("InvoiceWorkorders");

                    b.Navigation("WorkorderAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
