<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TinderWithStats.Frontend.Client\TinderWithStats.Frontend.Client.csproj" />

		<ProjectReference Include="..\gAPI\gAPI.AutoComponent\gAPI.AutoComponent.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\gAPI\gAPI.AutoPage\gAPI.AutoPage.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />

	</ItemGroup>

</Project>
