// <auto-generated />
using System;

namespace CodeGeneratorExample1
{
    public class HelloWorld
    {
        public static void SayHello()
        {
            Console.WriteLine($"Hello world! From reflection we found: Program, <>c");
        }
    }
}
