using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.IO;
using System.Linq;
using System.Text;

namespace CodeGeneratorExample3.Analyzer;

[Generator]
public class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Lees "Name.txt" uit de AdditionalFiles (optioneel bestand in hoofdproject)
        var nameFile = context.AdditionalTextsProvider
            .Where(file => Path.GetFileName(file.Path).Equals("Name.json", StringComparison.OrdinalIgnoreCase))
            .Select((file, ct) => file.GetText(ct)?.ToString())
            .Collect()
            .Select((configs, _) => configs.FirstOrDefault() ?? "Unknown");

        // Combineer de huidige compilatie met de bestandsinhoud
        var combined = context.CompilationProvider.Combine(nameFile);

        context.RegisterSourceOutput(combined, (spc, tuple) =>
        {
            try
            {
                var (compilation, nameText) = tuple;

                // Verzamel symbol-namen van top-level types in de huidige assembly
                var symbols = compilation.GlobalNamespace
                    .GetNamespaceMembers()
                    .SelectMany(ns => ns.GetTypeMembers())
                    .Select(t => t.Name)
                    .ToList();

                var joinedSymbols = symbols.Count == 0
                    ? "No symbols found"
                    : string.Join(", ", symbols);

                var generatedCode = $@"// <auto-generated />
using System;

namespace CodeGeneratorExample3
{{
    public static class HelloWorld
    {{
        public static void SayHello()
        {{
            Console.WriteLine(""Hello, {Escape(nameText)}!"");
            Console.WriteLine(""Compile-time reflection found types: {Escape(joinedSymbols)}"");
        }}
    }}
}}";

                spc.AddSource("HelloWorld.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                ShowError(ex, spc);
            }
        });
    }

    private static string Escape(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return "";
        return text.Replace("\"", "'").Replace("\r", "").Replace("\n", "");
    }

    public void ShowError(Exception exception, SourceProductionContext spc)
        => ShowError(exception.Message, spc);

    public void ShowError(string errorMessage, SourceProductionContext spc)
    {
        var src = $"#error {errorMessage.Replace("\r", "\\r").Replace("\n", "\\n")}";
        spc.AddSource("GeneratorError.g.cs", SourceText.From(src, Encoding.UTF8));
    }
}
