using System.Reflection;

namespace CodeGeneratorExample1.Generator;

internal class Program
{
    static void Main(string[] args)
    {
        // Zoek het hoofdprojectpad (relatief vanuit generator)
        var projectRoot = Path.Combine(Directory.GetParent(Directory.GetCurrentDirectory())!.Parent!.Parent!.FullName, "..", "CodeGeneratorExample1");
        var outputPath = Path.Combine(projectRoot, "HelloWorld.cs");

        // We gebruiken reflection om iets te 'halen' uit deze assembly
        var assembly = Assembly.GetExecutingAssembly();
        var classNames = assembly.GetTypes().Select(t => t.Name).ToArray();
        var joinedNames = string.Join(", ", classNames);

        // Bouw de code
        var code = $@"// <auto-generated />
using System;

namespace CodeGeneratorExample1
{{
    public class HelloWorld
    {{
        public static void SayHello()
        {{
            Console.WriteLine($""Hello world! From reflection we found: {joinedNames}"");
        }}
    }}
}}
";
        // Schrijf naar bestand
        File.WriteAllText(outputPath, code);

        Console.WriteLine($"✅ Generated file: {outputPath}");
    }
}
