// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinderWithStats.Backend.Entities;

#nullable disable

namespace TinderWithStats.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005091558_Toch maar datetime voor geboortedatum")]
    partial class Tochmaardatetimevoorgeboortedatum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TinderWithStats.Backend.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfileReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileSenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("ProfileReceiverId");

                    b.HasIndex("ProfileSenderId");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("MatchAccepted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("MatchCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProfileReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileSenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfileReceiverId");

                    b.HasIndex("ProfileSenderId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Beroep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.ProfilePicture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UploadDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfilePictures");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("LockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Ip<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ChangePasswordAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ChangePasswordLockedOutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ForgetPasswordAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ForgetPasswordLockedOutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LoginLockedOutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RegisterCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RegisterLockedOutDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Ips", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Route<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("RouteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Session<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIp<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IpId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IpId");

                    b.HasIndex("UserId");

                    b.ToTable("UserIps", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSession<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIpId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserIpId");

                    b.ToTable("UserIpSessions", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionToken<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIpSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserIpSessionId");

                    b.ToTable("UserIpSessionTokens", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRoute<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIpSessionTokenId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserIpSessionTokenId");

                    b.ToTable("UserIpSessionTokenRoutes", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRouteRequest<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<byte>("Day")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Hour")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<long>("UserIpSessionTokenRouteId")
                        .HasColumnType("bigint");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("UserIpSessionTokenRouteId");

                    b.ToTable("UserIpSessionTokenRouteRequests", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserToken<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.ChatMessage", b =>
                {
                    b.HasOne("TinderWithStats.Backend.Entities.Match", "Match")
                        .WithMany("ChatMessages")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TinderWithStats.Backend.Entities.Profile", "ProfileReceiver")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("ProfileReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TinderWithStats.Backend.Entities.Profile", "ProfileSender")
                        .WithMany("MessagesSend")
                        .HasForeignKey("ProfileSenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("ProfileReceiver");

                    b.Navigation("ProfileSender");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.Match", b =>
                {
                    b.HasOne("TinderWithStats.Backend.Entities.Profile", "ProfileReceiver")
                        .WithMany("MatchesReceived")
                        .HasForeignKey("ProfileReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TinderWithStats.Backend.Entities.Profile", "ProfileSender")
                        .WithMany("MatchesSend")
                        .HasForeignKey("ProfileSenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProfileReceiver");

                    b.Navigation("ProfileSender");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.Profile", b =>
                {
                    b.HasOne("TinderWithStats.Backend.Entities.Location", "Location")
                        .WithMany("Profiles")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TinderWithStats.Backend.Entities.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.ProfilePicture", b =>
                {
                    b.HasOne("TinderWithStats.Backend.Entities.Profile", "Profile")
                        .WithMany("ProfilePictures")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIp<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.Ip<TinderWithStats.Backend.Entities.User>", "Ip")
                        .WithMany("UserIps")
                        .HasForeignKey("IpId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TinderWithStats.Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Ip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSession<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.Session<TinderWithStats.Backend.Entities.User>", "Session")
                        .WithMany("UserIpSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("gAPI.Core.Server.Entities.UserIp<TinderWithStats.Backend.Entities.User>", "UserIp")
                        .WithMany("UserIpSessions")
                        .HasForeignKey("UserIpId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("UserIp");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionToken<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.UserToken<TinderWithStats.Backend.Entities.User>", "Token")
                        .WithMany("UserIpSessionTokens")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("gAPI.Core.Server.Entities.UserIpSession<TinderWithStats.Backend.Entities.User>", "UserIpSession")
                        .WithMany("UserIpSessionTokens")
                        .HasForeignKey("UserIpSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("UserIpSession");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRoute<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.Route<TinderWithStats.Backend.Entities.User>", "Route")
                        .WithMany("UserIpSessionTokenRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("gAPI.Core.Server.Entities.UserIpSessionToken<TinderWithStats.Backend.Entities.User>", "UserIpSessionToken")
                        .WithMany("UserIpSessionTokenRoutes")
                        .HasForeignKey("UserIpSessionTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("UserIpSessionToken");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRouteRequest<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.UserIpSessionTokenRoute<TinderWithStats.Backend.Entities.User>", "UserIpSessionTokenRoute")
                        .WithMany("UserIpSessionTokenRouteRequests")
                        .HasForeignKey("UserIpSessionTokenRouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserIpSessionTokenRoute");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserToken<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.HasOne("TinderWithStats.Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.Location", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.Match", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.Profile", b =>
                {
                    b.Navigation("MatchesReceived");

                    b.Navigation("MatchesSend");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSend");

                    b.Navigation("ProfilePictures");
                });

            modelBuilder.Entity("TinderWithStats.Backend.Entities.User", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Ip<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Navigation("UserIps");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Route<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokenRoutes");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Session<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessions");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIp<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessions");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSession<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokens");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionToken<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokenRoutes");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRoute<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokenRouteRequests");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserToken<TinderWithStats.Backend.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
